"-------------------Theme----------------------
set cursorline
"let g:airline_theme='transparent'		"airLine Theme
let g:airline_theme='simple'		"airLine Theme
let g:airline_powerline_fonts = 3
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled=1

colorscheme nas-tender
"colorscheme nas-ayu
"colorscheme nas

highlight Normal ctermbg=none guibg=none
highlight SignColumn ctermbg=none guibg=none
highlight LineNr ctermbg=none guibg=none
"----------------------------------------------

"1989.vim
"256-grayvim.vim
"256-jungle.vim
"256_noir.vim
"3dglasses.vim
"abbott.vim
"abra.vim
"adam.vim
"adaryn.vim
"adobe.vim
"adrian.vim
"advantage.vim
"adventurous.vim
"afterglow.vim
"af.vim
"aiseered.vim
"alduin.vim
"ancient.vim
"anderson.vim
"angr.vim
"anotherdark.vim
"ansi_blows.vim
"antares.vim
"apprentice.vim
"aquamarine.vim
"aqua.vim
"arcadia.vim
"archery.vim
"argonaut.vim
"ashen.vim
"asmanian2.vim
"asmanian_blood.vim
"asmdev2.vim
"asmdev.vim
"astronaut.vim
"asu1dark.vim
"Atelier_CaveDark.vim
"Atelier_CaveLight.vim
"Atelier_DuneDark.vim
"Atelier_DuneLight.vim
"Atelier_EstuaryDark.vim
"Atelier_EstuaryLight.vim
"Atelier_ForestDark.vim
"Atelier_ForestLight.vim
"Atelier_HeathDark.vim
"Atelier_HeathLight.vim
"Atelier_LakesideDark.vim
"Atelier_LakesideLight.vim
"Atelier_PlateauDark.vim
"Atelier_PlateauLight.vim
"Atelier_SavannaDark.vim
"Atelier_SavannaLight.vim
"Atelier_SeasideDark.vim
"Atelier_SeasideLight.vim
"Atelier_SulphurpoolDark.vim
"Atelier_SulphurpoolLight.vim
"atom.vim
"aurora.vim
"automation.vim
"autumnleaf.vim
"autumn.vim
"ayu.vim
"babymate256.vim
"badwolf.vim
"bandit.vim
"base16-ateliercave.vim
"base16-atelierdune.vim
"base16-atelierestuary.vim
"base16-atelierforest.vim
"base16-atelierheath.vim
"base16-atelierlakeside.vim
"base16-atelierplateau.vim
"base16-ateliersavanna.vim
"base16-atelierseaside.vim
"base16-ateliersulphurpool.vim
"base16-railscasts.vim
"base.vim
"basic-dark.vim
"basic-light.vim
"basic.vim
"baycomb.vim
"bayQua.vim
"bclear.vim
"beachcomber.vim
"beauty256.vim
"beekai.vim
"behelit.vim
"benlight.vim
"Benokai.vim
"bensday.vim
"billw.vim
"biogoo.vim
"birds-of-paradise.vim
"bitterjug.vim
"black_angus.vim
"blackbeauty.vim
"blackboard.vim
"blackdust.vim
"blacklight.vim
"BlackSea.vim
"Black.vim
"blaquemagick.vim
"blazer.vim
"blink.vim
"Blue2.vim
"bluechia.vim
"bluedrake.vim
"bluegreen.vim
"bluenes.vim
"blueprint.vim
"blueshift.vim
"blues.vim
"blue.vim
"bluez.vim
"blugrine.vim
"bluish.vim
"bmichaelsen.vim
"boa.vim
"bocau.vim
"bog.vim
"boltzmann.vim
"borland.vim
"breeze.vim
"breezy.vim
"brighton.vim
"briofita.vim
"broduo.vim
"brogrammer.vim
"brookstream.vim
"brown.vim
"bubblegum-256-dark.vim
"bubblegum-256-light.vim
"bubblegum.vim
"buddy.vim
"burnttoast256.vim
"busierbee.vim
"busybee.vim
"buttercream.vim
"bvemu.vim
"bw.vim
"c16gui.vim
"C64.vim
"cabin.vim
"cake16.vim
"cake.vim
"calmar256-dark.vim
"calmar256-light.vim
"camo.vim
"campfire.vim
"candycode.vim
"candyman.vim
"CandyPaper.vim
"candy.vim
"caramel.vim
"carrot.vim
"carvedwoodcool.vim
"carvedwood.vim
"cascadia.vim
"celtics_away.vim
"cgpro.vim
"chalkboard.vim
"chance-of-storm.vim
"charged-256.vim
"charon.vim
"Chasing_Logic.vim
"chela_light.vim
"cherryblossom.vim
"chlordane.vim
"ChocolateLiquor.vim
"ChocolatePapaya.vim
"chocolate.vim
"chroma.vim
"chrysoprase.vim
"clarity.vim
"cleanphp.vim
"cleanroom.vim
"clearance.vim
"cloudy.vim
"clue.vim
"cobalt2.vim
"cobaltish.vim
"cobalt.vim
"coda.vim
"codeblocks_dark.vim
"codeburn.vim
"codedark.vim
"CodeFactoryv3.vim
"codeschool.vim
"coffee.vim
"coldgreen.vim
"colorer.vim
"colorful256.vim
"colorful.vim
"colorsbox-faff.vim
"colorsbox-greenish.vim
"colorsbox-material.vim
"colorsbox-stblue.vim
"colorsbox-stbright.vim
"colorsbox-steighties.vim
"colorsbox-stnight.vim
"colorzone.vim
"contrastneed.vim
"contrasty.vim
"cool.vim
"corn.vim
"corporation.vim
"crayon.vim
"crt.vim
"crunchbang.vim
"cthulhian.vim
"custom.vim
"c.vim
"cyberpunk.vim
"d8g_01.vim
"d8g_02.vim
"d8g_03.vim
"d8g_04.vim
"Dark2.vim
"darkblack.vim
"darkblue2.vim
"darkblue.vim
"darkBlue.vim
"darkbone.vim
"darkburn.vim
"DarkDefault.vim
"darkdevel.vim
"darkdot.vim
"darkeclipse.vim
"darkerdesert.vim
"darker-robin.vim
"darkglass.vim
"darkocean.vim
"darkrobot.vim
"dark-ruby.vim
"darkslategray.vim
"darkspectrum.vim
"darktango.vim
"Dark.vim
"darkzen.vim
"darkZ.vim
"darth.vim
"dawn.vim
"deepsea.vim
"deep-space.vim
"default.vim
"delek.vim
"delphi.vim
"denim.vim
"derefined.vim
"desert256v2.vim
"desert256.vim
"desertedoceanburnt.vim
"desertedocean.vim
"desertEx.vim
"desertink.vim
"desert.vim
"despacio.vim
"detailed.vim
"deus.vim
"devbox-dark-256.vim
"DevC++.vim
"Dev_Delight.vim
"deveiate.vim
"developer.vim
"Dim2.vim
"DimBlue.vim
"DimGreens.vim
"DimGreen.vim
"DimGrey.vim
"DimRed.vim
"DimSlate.vim
"Dim.vim
"diokai.vim
"disciple.vim
"distill.vim
"distinguished.vim
"django.vim
"donbass.vim
"donttouchme.vim
"doorhinge.vim
"doriath.vim
"dracula_bold.vim
"dracula.vim
"dual.vim
"dull.vim
"duotone-darkcave.vim
"duotone-darkdesert.vim
"duotone-darkearth.vim
"duotone-darkforest.vim
"duotone-darkheath.vim
"duotone-darklake.vim
"duotone-darkmeadow.vim
"duotone-darkpark.vim
"duotone-darkpool.vim
"duotone-darksea.vim
"duotone-darkspace.vim
"duotone-dark.vim
"dusk.vim
"dw_blue.vim
"dw_cyan.vim
"dw_green.vim
"dw_orange.vim
"dw_purple.vim
"dw_red.vim
"dw_yellow.vim
"dzo.vim
"earendel.vim
"earthburn.vim
"earth.vim
"eclipse.vim
"eclm_wombat.vim
"ecostation.vim
"editplus.vim
"edo_sea.vim
"ego.vim
"eink.vim
"ekinivim.vim
"ekvoli.vim
"eldar.vim
"elda.vim
"elflord.vim
"elise.vim
"elisex.vim
"elrodeo.vim
"elrond.vim
"emacs.vim
"enigma.vim
"enzyme.vim
"erez.vim
"eva01-LCL.vim
"eva01.vim
"eva.vim
"evening1.vim
"evening.vim
"evokai.vim
"evolution.vim
"fahrenheit.vim
"fairyfloss.vim
"falcon.vim
"far.vim
"felipec.vim
"feral.vim
"fight-in-the-shade.vim
"fine_blue.vim
"firewatch.vim
"flatcolor.vim
"flatlandia.vim
"flatland.vim
"flattened_dark.vim
"flattened_light.vim
"flattown.vim
"flattr.vim
"flatui.vim
"fnaqevan.vim
"fog.vim
"fokus.vim
"forneus.vim
"foursee.vim
"freya.vim
"frood.vim
"frozen.vim
"fruidle.vim
"fruit.vim
"fruity.vim
"fu.vim
"fx.vim
"gardener.vim
"garden.vim
"gemcolors.vim
"genericdc-light.vim
"genericdc.vim
"gentooish.vim
"getafe.vim
"getfresh.vim
"ghostbuster.vim
"github.vim
"gobo.vim
"golded.vim
"golden.vim
"goodwolf.vim
"google.vim
"gor.vim
"gotham256.vim
"gotham.vim
"gothic.vim
"grape.vim
"gravity.vim
"grayorange.vim
"graywh.vim
"greens.vim
"Green.vim
"greenvision.vim
"greenwint.vim
"grey2.vim
"greyblue.vim
"greygull.vim
"grishin.vim
"gruvbox.vim
"gryffin.vim
"guardian.vim
"guepardo.vim
"h80.vim
"habiLight.vim
"happy_hacking.vim
"harlequin.vim
"heliotrope.vim
"hemisu.vim
"herald.vim
"herokudoc-gvim.vim
"herokudoc.vim
"heroku-terminal.vim
"heroku.vim
"hhazure.vim
"hhdblue.vim
"hhdcyan.vim
"hhdgray.vim
"hhdgreen.vim
"hhdmagenta.vim
"hhdred.vim
"hhdyellow.vim
"hhorange.vim
"hhpink.vim
"hhspring.vim
"hhteal.vim
"hhviolet.vim
"highlighter_term_bright.vim
"highlighter_term.vim
"highwayman.vim
"hilal.vim
"holokai.vim
"hornet.vim
"horseradish256.vim
"hotpot.vim
"hual.vim
"hybrid-light.vim
"hybrid_material.vim
"hybrid_reverse.vim
"hybrid.vim
"hydrangea.vim
"iangenzo.vim
"ibmedit.vim
"icansee.vim
"iceberg.vim
"immortals.vim
"impactG.vim
"impactjs.vim
"impact.vim
"industrial.vim
"industry.vim
"ingretu.vim
"inkpot.vim
"inori.vim
"ir_black.vim
"ironman.vim
"itg_flat_transparent.vim
"itg_flat.vim
"itsasoa.vim
"jaime.vim
"jammy.vim
"janah.vim
"japanesque.vim
"jelleybeans.vim
"jellybeans.vim
"jellygrass.vim
"jellyx.vim
"jhdark.vim
"jhlight.vim
"jiks.vim
"jitterbug.vim
"kalahari.vim
"kalisi.vim
"kaltex.vim
"kalt.vim
"kate.vim
"kellys.vim
"khaki.vim
"kib_darktango.vim
"kib_plastic.vim
"kings-away.vim
"kiss.vim
"kkruby.vim
"koehler.vim
"kolor.vim
"kruby.vim
"kyle.vim
"laederon.vim
"lakers_away.vim
"landscape.vim
"lanzarotta.vim
"lapis256.vim
"late_evening.vim
"lazarus.vim
"legiblelight.vim
"leglight2.vim
"leo.vim
"less.vim
"lettuce.vim
"leya.vim
"lightcolors.vim
"LightDefaultGrey.vim
"LightDefault.vim
"lightning.vim
"LightTan.vim
"Light.vim
"LightYellow.vim
"lilac.vim
"lilydjwg_dark.vim
"lilydjwg_green.vim
"lilypink.vim
"lingodirector.vim
"liquidcarbon.vim
"literal_tango.vim
"lizard256.vim
"lizard.vim
"lodestone.vim
"loogica.vim
"louver.vim
"lucid.vim
"lucius.vim
"luinnar.vim
"lumberjack.vim
"luna-term.vim
"luna.vim
"lxvc.vim
"lyla.vim
"mac_classic.vim
"macvim-light.vim
"made_of_code.vim
"madeofcode.vim
"magellan.vim
"magicwb.vim
"mango.vim
"manuscript.vim
"manxome.vim
"marklar.vim
"maroloccio2.vim
"maroloccio3.vim
"maroloccio.vim
"mars.vim
"martin_krischik.vim
"materialbox.vim
"material-theme.vim
"materialtheme.vim
"material.vim
"matrix.vim
"maui.vim
"mayansmoke.vim
"mdark.vim
"mellow.vim
"messy.vim
"meta5.vim
"metacosm.vim
"midnight.vim
"miko.vim
"minimalist.vim
"minimal.vim
"mint.vim
"mizore.vim
"mod8.vim
"mod_tcsoft.vim
"mohammad.vim
"mojave.vim
"molokai_dark.vim
"molokai.vim
"monoacc.vim
"monochrome.vim
"monokai-chris.vim
"monokain.vim
"monokai-phoenix.vim
"Monokai.vim
"montz.vim
"moody.vim
"moonshine_lowcontrast.vim
"moonshine_minimal.vim
"moonshine.vim
"mophiaDark.vim
"mophiaSmoke.vim
"mopkai.vim
"more.vim
"moriarty.vim
"moria.vim
"morning.vim
"moss.vim
"motus.vim
"MountainDew.vim
"mourning.vim
"mrkn256.vim
"mrpink.vim
"mud.vim
"muon.vim
"murphy.vim
"mushroom.vim
"mustang.vim
"mythos.vim
"native.vim
"nature.vim
"navajo-night.vim
"navajo.vim
"nazca.vim
"nedit2.vim
"nedit.vim
"nefertiti.vim
"neodark.vim
"neon.vim
"neonwave.vim
"nerv-ous.vim
"nes.vim
"nets-away.vim
"neuromancer.vim
"neutron.vim
"neverland2-darker.vim
"neverland2.vim
"neverland-darker.vim
"neverland.vim
"neverness.vim
"nevfn.vim
"new-railscasts.vim
"newspaper.vim
"newsprint.vim
"nicotine.vim
"nightflight2.vim
"nightflight.vim
"nightshade_print.vim
"nightshade.vim
"nightshimmer.vim
"nightsky.vim
"night.vim
"night_vision.vim
"nightVision.vim
"nightwish.vim
"noclown.vim
"nocturne.vim
"nofrils-acme.vim
"nofrils-dark.vim
"nofrils-light.vim
"nofrils-sepia.vim
"no_quarter.vim
"nordisk.vim
"nord.vim
"northland.vim
"northpole.vim
"northsky.vim
"norwaytoday.vim
"nour.vim
"nuvola.vim
"obsidian2.vim
"obsidian.vim
"oceanblack256.vim
"oceanblack.vim
"oceandeep.vim
"OceanicNextLight.vim
"OceanicNext.vim
"oceanlight.vim
"off.vim
"olive.vim
"onedark.vim
"orange.vim
"osx_like.vim
"otaku.vim
"oxeded.vim
"pablo.vim
"pacific.vim
"paintbox.vim
"PapayaWhip.vim
"PaperColor.vim
"paramount.vim
"parsec.vim
"peachpuff.vim
"peaksea.vim
"pencil.vim
"penultimate.vim
"peppers.vim
"PerfectDark.vim
"perfect.vim
"petrel.vim
"pf_earth.vim
"phd.vim
"phoenix.vim
"phphaxor.vim
"phpx.vim
"pink.vim
"pixelmuerto.vim
"plasticine.vim
"playroom.vim
"pleasant.vim
"potts.vim
"predawn.vim
"preto.vim
"pride.vim
"primaries.vim
"primary.vim
"print_bw.vim
"prmths.vim
"professional.vim
"proton.vim
"ps_color.vim
"pspad.vim
"pt_black.vim
"putty.vim
"pw.vim
"py-darcula.vim
"pyte.vim
"python.vim
"quagmire.vim
"quantum.vim
"radicalgoodspeed.vim
"raggi.vim
"railscasts.vim
"rainbow_autumn.vim
"rainbow_fine_blue.vim
"rainbow_fruit.vim
"rainbow_night.vim
"rainbow_sea.vim
"rakr-light.vim
"random.vim
"rastafari.vim
"rcg_gui.vim
"rcg_term.vim
"rdark-terminal.vim
"rdark.vim
"redblack.vim
"redstring.vim
"Red.vim
"refactor.vim
"relaxedgreen.vim
"reliable.vim
"reloaded.vim
"revolutions.vim
"Revolution.vim
"robinhood.vim
"rockets-away.vim
"ron.vim
"rootwater.vim
"sadek1.vim
"sand.vim
"sandydune.vim
"satori.vim
"saturn.vim
"scheakur.vim
"scite.vim
"scooby.vim
"seagull.vim
"sean.vim
"seashell.vim
"seattle.vim
"selenitic.vim
"seoul256-light.vim
"seoul256.vim
"seoul.vim
"SerialExperimentsLain.vim
"seti.vim
"settlemyer.vim
"sexy-railscasts.vim
"sf.vim
"shadesofamber.vim
"shades-of-teal.vim
"shine.vim
"shiny-white.vim
"shobogenzo.vim
"sialoquent.vim
"sienna.vim
"sierra.vim
"sift.vim
"silent.vim
"simple256.vim
"simpleandfriendly.vim
"simple_b.vim
"simple_dark.vim
"simplewhite.vim
"simplon.vim
"skittles_autumn.vim
"skittles_berry.vim
"skittles_dark.vim
"sky.vim
"slate2.vim
"SlateDark.vim
"Slate.vim
"smarties.vim
"smpl.vim
"smp.vim
"smyck.vim
"soda.vim
"softbluev2.vim
"softblue.vim
"softlight.vim
"solarized8_dark_flat.vim
"solarized8_dark_high.vim
"solarized8_dark_low.vim
"solarized8_dark.vim
"solarized8_light_flat.vim
"solarized8_light_high.vim
"solarized8_light_low.vim
"solarized8_light.vim
"solarized.vim
"sole.vim
"sol-term.vim
"sol.vim
"sonofobsidian.vim
"sonoma.vim
"sorcerer.vim
"soruby.vim
"soso.vim
"sourcerer.vim
"southernlights.vim
"southwest-fog.vim
"spacegray.vim
"spacemacs-theme.vim
"space-vim-dark.vim
"spartan.vim
"spectro.vim
"spiderhawk.vim
"Spink.vim
"spring-night.vim
"spring.vim
"sprinkles.vim
"spurs_away.vim
"srcery-drk.vim
"srcery.vim
"stackoverflow.vim
"stefan.vim
"stereokai.vim
"stingray.vim
"stonewashed-256.vim
"stonewashed-dark-256.vim
"stonewashed-dark-gui.vim
"stonewashed-gui.vim
"stormpetrel.vim
"strange.vim
"strawimodo.vim
"summerfruit256.vim
"summerfruit.vim
"sunburst.vim
"surveyor.vim
"swamplight.vim
"sweater.vim
"SweetCandy.vim
"symfony.vim
"synic.vim
"synthwave.vim
"tabula.vim
"tango2.vim
"tango-desert.vim
"tango-morning.vim
"tangoshady.vim
"tango.vim
"tangoX.vim
"taqua.vim
"tatami.vim
"tayra.vim
"tchaba2.vim
"tchaba.vim
"tcsoft.vim
"telstar.vim
"tender.vim
"termschool.vim
"tesla.vim
"tetragrammaton.vim
"textmate16.vim
"thegoodluck.vim
"thermopylae.vim
"thestars.vim
"thornbird.vim
"thor.vim
"tibet.vim
"tidy.vim
"tigrana-256-dark.vim
"tigrana-256-light.vim
"tir_black.vim
"tolerable.vim
"tomatosoup.vim
"Tomorrow-Night-Blue.vim
"Tomorrow-Night-Bright.vim
"Tomorrow-Night-Eighties.vim
"Tomorrow-Night.vim
"Tomorrow.vim
"tony_light.vim
"toothpik.vim
"torte.vim
"transparent.vim
"triplejelly.vim
"trivial256.vim
"trogdor.vim
"tropikos.vim
"true-monochrome.vim
"turbo.vim
"turtles.vim
"tutticolori.vim
"twilight256.vim
"twilight.vim
"twitchy.vim
"two2tango.vim
"two-firewatch.vim
"ubaryd.vim
"ubloh.vim
"umber-green.vim
"understated.vim
"underwater-mod.vim
"underwater.vim
"unicon.vim
"up.vim
"vanzan_color.vim
"vcbc.vim
"vc.vim
"vertLaiton.vim
"vexorian.vim
"vibrantink.vim
"vice.vim
"vilight.vim
"vimbrains.vim
"vimbrant.vim
"vimicks.vim
"vim-material.vim
"visualstudio.vim
"vividchalk.vim
"VIvid.vim
"vj.vim
"void.vim
"vorange.vim
"vydark.vim
"vylight.vim
"wargrey.vim
"warm_grey.vim
"warriors-away.vim
"wasabi256.vim
"watermark.vim
"wellsokai.vim
"welpe.vim
"White2.vim
"whitebox.vim
"whitedust.vim
"white.vim
"widower.vim
"wikipedia.vim
"win9xblueback.vim
"winterd.vim
"wintersday.vim
"winter.vim
"woju.vim
"wolfpack.vim
"wombat256dave.vim
"wombat256i.vim
"wombat256mod.vim
"wombat256.vim
"wombat.vim
"wood.vim
"wuye.vim
"wwdc16.vim
"wwdc17.vim
"xcode-default.vim
"xcode.vim
"xedit.vim
"xemacs.vim
"xian.vim
"xmaslights.vim
"xoria256.vim
"xterm16.vim
"yeller.vim
"yuejiu.vim
"zazen.vim
"zellner.vim
"zenburn.vim
"zenesque.vim
"zen.vim
"zephyr.vim
"zmrok.vim
"znake.vim
